version: '3'
services:
  # node:
  #   image: ng_test 
  #   ports:
  #     - 4200:4200
  dima_api:
    image: dima_api 
    ports: 
      - "5005:5005"

  dima_check:
    image: dima_check 
    ports: 
      - "4201:80"

  main_api:
    image: api2

    deploy:
      update_config:
        order: start-first
        failure_action: rollback
        delay: 10s
      restart_policy:
        condition: any
        delay: 5s
        max_attempts: 3
        window: 120s
    ports: 
      - "5002:5002"
    env_file: 
      - /home/kris/apiv2/node.env 
  nri_api:
    image: nri_api
    ports:
      - "5010:5010"
    env_file: 
      - /home/kris/nri_api/.env
# 
# sudo docker stack deploy --compose-file docker-compose.yml api_services
# to check stack:
## sudo docker stack ls 
# to check individual services: 
## sudo docker service ls