version: '3'
services:
  # node:
  #   image: ng_test 
  #   ports:
  #     - 4200:4200
  dima_api:
    image: dima_api 
    ports: 
      - "5005:5005"

  dima_check:
    image: dima_check 
    ports: 
      - "4201:80"

  main_api:
    image: api2
    ports: 
      - "5002:5002"
    env_file: 
      - /home/kris/main_api/node.env 
  nri_api:
    image: nri_api
    ports:
      - "5010:5010"
    env_file: 
      - /home/kris/nri_api/.env
      
  met_api:
    image: met_api 
    ports:
      - "5013:5013"
    env_file: 
      - /home/kris/met_api/.env
      
  aero_api:
    image: aero_api
    ports:
      - "5015:5015"
    env_file: 
      - /home/kris/aero_api/.env
# 
# sudo docker stack deploy --compose-file docker-compose.yml api_services
# to check stack:
## sudo docker stack ls 
# to check individual services: 
## sudo docker service ls