/* jshint indent: 1 */

export interface dataGap {
	LineKey : string ;
     RecKey : string ;
     DateModified : Date ;
     FormType : string ;
     FormDate : Date ;
     Observer : string ;
     Recorder : string ;
     DataEntry : string ;
     DataErrorChecking : string ;
     Direction : number ;
     Measure : number ;
     LineLengthAmount : number ;
     GapMin : number ;
     GapData : number ;
     PerennialsCanopy : number ;
     AnnualGrassesCanopy : number ;
     AnnualForbsCanopy : number ;
     OtherCanopy : number ;
     Notes : string ;
     NoCanopyGaps : number ;
     NoBasalGaps : number ;
     PerennialsBasal : number ;
     AnnualGrassesBasal : number ;
     AnnualForbsBasal : number ;
     OtherBasal : number ;
     PrimaryKey : string ;
     DBKey : string ;
     SeqNo : string ;
     RecType : string ;
     GapStart : number ;
     GapEnd : number ;
     Gap : number ;
     source : string ;
     State : string ;
     PlotKey : string ;
		 DateLoadedInDb : Date ;
}
